[package]
name = "day18"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

[lib]
name = "day18lib"
path = "src/lib.rs"

[[bin]]
name = "day18bin"
path = "src/main.rs"

[dependencies]
