[package]
name = "day11"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
color-eyre = "0.5.11"
itertools = "0.10.0"
structopt = "0.3.21"
thiserror = "1.0.24"
