[package]
name = "day22"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

[lib]
name = "day22lib"
path = "src/lib.rs"

[[bin]]
name = "day22bin"
path = "src/main.rs"

[dependencies]
