[package]
name = "day04"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.5.4"
lazy_static = "1.4.0"
counter = "0.5.2"
