[package]
name = "day24"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

[lib]
name = "day24lib"
path = "src/lib.rs"

[[bin]]
name = "day24bin"
path = "src/main.rs"

[dependencies]
