[package]
name = "day05"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

[lib]
name = "day05lib"
path = "src/lib.rs"

[[bin]]
name = "day05bin"
path = "src/main.rs"

[dependencies]
rust-crypto = "^0.2"
